# TP n°2: Crypter et décrypter un fichier

**But:** : Dans ce TP, nous allons voir des techniques simple pour crypter, décrypter et casser le cryptage d'un code. On abordera en plus la notion de fonction (que l'on verra bientôt en cours) et comment lire et écrire sur un fichier. 

## étape 1: coder et décoder un mot avec un code ASCII. 

### Coder le mot 

Comme nous avions vu en cours, il existe un ordre précis pour les différents caractères. Celui-ci est lié directement au code ascii de ce caractère. Vous pouvez trouver la correspondance dans le fichier table_ascii. 
Il existe une fonction python qui permet d'obtenir le code ascii d'un caractère. Cette fonction est ord(). ord("a"), vous renverra le numéro du caractère "a". 

*exercice:* 
1. Déterminer le code ascii des caractères suivant: a, d ,A, F, 2 et \[
2. Essayer les commandes: ord("AA"), ord(a) et ord(2). Pourquoi ne marchent-t-elles pas ?

*exercice:*

À l'aide d'une boucle for, faites un petit programme qui permet de remplacer un mot en une suite de caractères ASCII. On fera en sorte qu'il y ait un espace entre chaque numéro et que le mot à chiffrer soit une variable. 

aide: 
1. Les chaines de caractères peuvent être concaténées c'est à dire collées en faisant juste +
2. Les nombres ascii devrais être traités comme des chaines de caractères.

In [41]:
mot= "Hello"
mot_chiffrer=""
for i in mot: 
    mot_chiffrer += " "+str(ord(i))
print(mot_chiffrer)

 72 101 108 108 111


### Déchiffrer le mot 

La première chose à apprendre c'est à décoder une lettre: pour se faire il suffit d'utiliser la fonction chr(). 
Elle fait appel à un entier et la transforme en lettre. Exemple: chr(72) donne "H". 

Décoder un mot complet n'est pas facile. Nous allons y aller par étape: 

*étape 1*: lire la première lettre 

À l'aide d'une boucle while: créer un petit programme qui lit les premiers chiffres d'un mot chiffré et s'arrête quand il trouve un espace (donc quand la première lettre est finie) ou que c'est la fin du mot chiffré. Il affichera les chiffres trouvés 

exemple: pour le mot chiffré: "72 101 108 108 111", votre programme doit afficher "72"

*étape 2*: déchiffrer la première lettre

Compléter votre programme de façon qu'à la place du nombre correspondant à la première lettre, il vous affiche la première lettre. 

exemple: pour le mot chiffré: "72 101 108 108 111", votre programme doit afficher "H"



In [2]:
mot_chiffrer="72 101 108 108 111"
mot=""
lettre=""
pos=0

while pos<len(mot_chiffrer) and mot_chiffrer[pos] != " ":
    lettre+=mot_chiffrer[pos]
    pos=pos+1
print(chr(int(lettre)))


H


*étape 3:* déchiffrer la prochaine lettre et afficher le début du mot. 

Maintenant que l'on sait déchiffrer la première lettre, il faut passer à la suivante. 

Pour faire ça, il suffit de recommencer votre boucle while mais en ne partant plus de la position 0 mais de la position juste après le premier espace trouvé.

Faite en sorte que votre programme affiche le début du mot.

exemple: pour le mot chiffré: "72 101 108 108 111", votre programme doit afficher "He"


In [3]:
mot_chiffrer="72 101 108 108 111"
mot=""
lettre=""
pos=0

while pos<len(mot_chiffrer) and mot_chiffrer[pos] != " ":
    lettre+=mot_chiffrer[pos]
    pos=pos+1
print(chr(int(lettre)))

pos+=1 
mot+=chr(int(lettre))
lettre=""

while pos<len(mot_chiffrer) and mot_chiffrer[pos] != " ":
    lettre+=mot_chiffrer[pos]
    pos=pos+1
print(chr(int(lettre)))
mot+=chr(int(lettre))
print(mot)

H
e
He


étape 4: Déchiffrer le mot complet. 

À l'aide d'une boucle, faites en sorte que votre programme déchiffre le mot complet.

In [4]:
mot_chiffrer="72 101 108 108 111"
mot=""
lettre=""
pos=0
while pos<len(mot_chiffrer):
    while pos<len(mot_chiffrer) and mot_chiffrer[pos] != " ":
        lettre+=mot_chiffrer[pos]
        pos=pos+1
    mot+=chr(int(lettre))
    lettre=""
    pos+=1
print(mot)

Hello


### Vos fonctions coder et encoder. 

En Python, il est possible de créer vos propres fonctions. Ce qui est très pratique pour ne pas à avoir à recopier des morceaux de code. (Moins on copie, plus il est facile de repérer et corriger les bugs)

Pour définir une fonction faisant appelle à un argument, on le fait de la façon suivante: 

def fonction(arg): # Défintion de la fonction

    code.... # Ce que fait la fonction 

    return resultat: # On sort le résultat
    
exemple: 

In [5]:
def plus3(nombre):
    res= nombre +3
    return res 

neuf=plus3(6)
douze=plus3(neuf)

print(neuf, douze)
    

9 12


on remarque: 

+ "def":  devant la fonction qui permet de dire que c'est une défnition
+ ":": qui permette de dire que la fonction commence. 
+ "return": qui permet de donner le résultat de la fonction 

**Exercice:**
écrire une fonction qui multiplie un nombre par 7. 


**Exercice**: Définir deux fonctions (il s'agit de mettre les minis-porgrammes dans des fonctions): 

+ La fonction chiffrer() qui permet de chiffrer un mot. L'argument sera le mot et elle retourne le mot chiffré. 
+ La fonction dechiffrer() qui permet de déchiffrer un mot chiffré. L'argument sera le mot chiffré et elle retourne le mot déchiffré.

Essayer vos fonctions en prennant un mot ou une phrase en la chiffrant et en la déchiffrant.

In [42]:
def dechiffrer(mot_chiffrer):
    mot=""
    lettre=""
    pos=0
    while pos<len(mot_chiffrer):
        while pos<len(mot_chiffrer) and mot_chiffrer[pos] != " ":
            lettre+=mot_chiffrer[pos]
            pos=pos+1
        mot+=chr(int(lettre))
        lettre=""
        pos+=1
    return mot

def chiffrer(mot):
    mot_chiffrer=""
    for i in mot: 
        mot_chiffrer += str(ord(i))+" "
    return mot_chiffrer

mot_ini="Hello, je m'appelle Arthur"
mot_chif=chiffrer(mot_ini)
print(mot_chif)
mot_f=dechiffrer(mot_chif)
print(mot_f)

72 101 108 108 111 44 32 106 101 32 109 39 97 112 112 101 108 108 101 32 65 114 116 104 117 114 
Hello, je m'appelle Arthur


## Encoder et Décoder un fichier

**Ouvrir un fichier:** 
Pour ouvrir un fichier c'est particulièrement simple en python. Il suffit de taper:
fichier = open('nom_du_fichier', option)

*"nom_du_fichier":* étant le chemin du fichier puis son nom. Pour un fichier qui est déjà dans le dossier dans lequel vous travailler, c'est juste son nom. 

*option:* étant les options d'ouverture du fichier. "r" est pour readable, vous l'ouvrez en lecture seulement. "w" est pour writable, vous pouvez écrire dessus (attention efface le fichier existant). "w+" permet d'écrire à la suite du fichier. "x" est pour executable, si c'est un programme vous pouvez l'exécuter.  

Si le fichier n'existe pas, il sera créé.

exemple: 
fichier_exemple = open('text.txt',"r") # ouvre le fichier text.txt en lecture seule et le désigne dans le code par le nom fichier_exemple 

**Lire un fichier:**

Pour lire un fichier, il suffit de taper fichier.read()

exemple: 

fichier_exemple.read()

Le mieux est d'enregistrer le contenu du fichier dans une variable pour que ça soit utile. 
exemple: 
text=fichier_exemple.read()

Je peux alors l'afficher en faisant print(text)

**Écrire dans un fichier**

Pour écrire dans un fichier, il faut d'abord l'avoir ouvert en mode écriture.

exemple: fichier_ecriture = open('text_2.txt',"w")

Ensuite il suffit d'utiliser la fonction print avec l'option file

exemple: print(text, file=fichier_ecriture)

*ATTENTION*: Pour voir le text apparaître dans le fichier, il faut fermer le fichier. 

exemple: fichier_ecriture.close()

**Exercice:**

1. Ouvrez le fichier Hooverphonic.txt et afficher son texte. 
2. Dans un fichier Madaboutyou.txt écrire le texte présent dans le fichier Hooverphonic.txt


In [10]:
fichier1 = open('Hooverphonic.txt',"r")
text = fichier1.read()
print(text)
fichier2 = open('Madaboutyou.txt',"w")
print(text, file=fichier2)
fichier2.close()

Hooverphonic Lyrics
"Mad About You"

Feel the vibe, feel the terror, feel the pain
It's driving me insane
I can't fake for God's sake, why am I
Driving in the wrong lane

Trouble is my middle name
But in the end I'm not too bad
Can someone tell me if it's wrong to be
So mad about you, mad about you, mad

Are you the fishy wine who will give me
A headache in the morning
Or just a dark blue land mine
That'll explode without a decent warning

Give me all your true hate
And I'll translate it in our bed
Into never seen passion, never seen passion
That's why I am
So mad about you, mad about you, mad

Trouble is your middle name
But in the end you're not too bad
Can someone tell me if it's wrong to be
So mad about you, mad about you
Mad about you, mad about you, mad

Give me all your true hate
And I'll translate it in our bed
Into never seen passion
That is why I am
So mad about you, mad about you
Mad about you, mad about you
Mad about you, mad about you, mad about you




**Exercice**

Chiffrer le texte contenu dans Hooverphonics.txt et le sauvegarder dans un fichier nommer Hoover_encrypt.txt 


In [ ]:
fichier1 = open('Hooverphonic.txt',"r")
text = fichier1.read()
text_chiffrer=chiffrer(text)
fichier2 = open('Hoover_encrypt.txt',"w")
print(text_chiffrer, file=fichier2)
fichier2.close()

**Exercice**

Créer une fonction qui prend le nom d'un fichier comme argument et crée un fichier chiffré contenant le texte du premier fichier et le fichier sera nommé "nom_crypt.txt" où "nom" doit être remplacé par le nom du fichier.

Tester-là sur le fichier Hoover.

In [13]:
def chiff_fichier(nom):
    fichier1 = open(nom,"r")
    text = fichier1.read()
    text_chiffrer=chiffrer(text)
    fichier2 = open(nom+"_crypt.txt","w")
    print(text_chiffrer, file=fichier2)
    fichier2.close()
    
chiff_fichier("weeknd.txt")


    

**Exercice**

Déchiffrer le fichier mystere1.txt

## Chiffrage par décalage

L'idée de ce code est relativement facile. Il s'agit de décaler les lettres d'un nombre que l'on appelera:  clé. Par exemple, si on a une clé de 3. Alors le A devient un D, le B devient un E, le C devient un F et ainsi de suite... 

Ainsi le mot CHEVAL deviendrait FKHYDO, le rendant illisible. 

**Exercice** 

1. En passant par le code ASCII des lettres, créer une fonction qui encode un mot (donné en argument) pour une clé donnée en argument. 

2. De même créer une fonction qui décode le mot grâce à la clé. (les arguments seront le mot chiffré et la clé) 


In [40]:
def chiffrage(mot,cle):
    mot_chi=""
    for i in mot:
        nbr= ord(i)
        nbr+=cle
        mot_chi+=str(chr(nbr))
    return mot_chi

def dechiffrage(mot_chi,cle):
    cle_inv=-cle
    return chiffrage(mot_chi,cle_inv)
mot="CHEVAL"
print(" ")      
print(mot)
a=chiffrage(mot,3)
print(a)
print(dechiffrage(a,3))
        

 
CHEVAL
FKHYDO
CHEVAL


**Exercice**

Faire une fonction qui permet de chiffrer un fichier et une qui permet de déchiffrer un fichier avec la clé. 
Les caractères de retour à la ligne "\n" ne seront pas transformés.


In [10]:
def chiffrage_fichier(nom_fichier,cle):
    fichier=open(nom_fichier,"r")
    text =  fichier.read()
    text_chi =""
    for i in text:
        if i == "\n":
            text_chi+=i
        else:
            nbr= ord(i)
            nbr+=cle
            text_chi+=str(chr(nbr))
    fichier_chi=open(nom_fichier+"_chi.txt","w")
    print(text_chi, file=fichier_chi)
    fichier_chi.close()

chiffrage_fichier("L'homme_presse",7)


In [8]:
def dechiffrage_fichier(fichier_chi,cle):
    cle_inv=-cle
    chiffrage_fichier(fichier_chi,cle_inv)
    
dechiffrage_fichier("Dormeur.txt_chi.txt",12)

## Allez plus loin

### Craquez le chiffrage

Pour craquer ce genre de chiffrage, une possibilité est d'étudier la statistique d'un texte. C'est à dire de regarder quel caractère revient le plus souvent. Dans un texte en français, les deux caractères les plus fréquent sont " " et "e". 
Ainsi le caractère revenant le plus souvent dans la version codé a de grande chance d'être " ". En faisant la différence  du nombre ASCII du caractère le plus fréquent et  celui de " ", on trouve la clé et on peut déchiffrer facilement. 

**Exercice**

Dans le code suivant, j'ai cronstruit deux fonctions. 
   
   1. stat_fichier: elle prend comme argument le nom du ficher et en resort un dictionnaire (type de stockage de donnée Python un peu particulier) contenant le nombres de fois qu'un caractère est présent dans le fichier. 
   2. maximum: prend un dictionnaire en entrée et ressort le caractère avec le plus grand nombre d'utilisations. 
   
Se servir de ces deux fonctions (sans les modifier) pour créer une fonction de craquage vous donnant la clé.


In [11]:
def stat_fichier(nom):
    fichier_stat=open(nom)
    text =  fichier_stat.read()
    text= text.lower()

    dict={}
    for i in text:
        if i in dict.keys():
            dict[i] += 1
        else:
            dict[i] = 1
            
    return dict

def maximum(dict):
    
    max=0; 
    for i in dict.keys():
        if dict[i] > max:
            max=dict[i]
            carac=i
    return carac

d=stat_fichier("mystere2.txt")
print(d)
a=maximum(d)
print(a)
print(ord(a)-ord(" "))
dechiffrage_fichier("mystere2.txt",7)

{'l': 197, 'u': 96, 'j': 41, 'v': 97, 'y': 90, "'": 258, '|': 114, 'q': 30, 'z': 135, 's': 52, 'ï': 8, '}': 18, 'h': 71, 'w': 28, '{': 62, 'm': 15, '\n': 45, 'k': 41, 't': 46, 'ñ': 6, '3': 10, 'p': 80, 'o': 15, '†': 30, 'ð': 4, 'ā': 3, 'i': 5, 'x': 22, '\x7f': 9, 'n': 9, 'ç': 5, '\x80': 1, 'a': 2, '\x81': 1}
'
7


### Codez que avec des lettres

**Exercice**

Modifier vos codes de chiffrage par décalage pour que le fichier de sorti ne contienne que des lettres et que les espaces ne soient pas modifiés ainsi que la ponctuation.

In [ ]:
def chiffrage_fichier_lettres(nom_fichier,cle):
    fichier=open(nom_fichier,"r")
    text =  fichier.read()
    text_chi =""
    for i in text:
        if (ord(i) not in range(65,91)) or (ord(i) not in range(97,123)): # Si i n'est pas une lettre, je ne le change pas 
            text_chi+=i
        else:
# Je dois faire en sorte que la transformation de i reste dans l'alphabet. Donc si ord(i) 
# sort des limites des nombres ascii correspondant aux lettres, je lui soustrait 26 
            nbr= ord(i)
            nbr+=cle
            if (nbr> 90 and nbr <97) or nbr > 122:
                nbr-=26
            text_chi+=str(chr(nbr))
    fichier_chi=open(nom_fichier+"_chi_let.txt","w")
    print(text_chi, file=fichier_chi)
    fichier_chi.close()

chiffrage_fichier("Hooverphonic.txt",7)

### Un codage moins facile à craquer

Il est possible de légèrement modifier l'encodage pour qu'il soit plus difficile à cracker. L'idée est de faire en sorte que la clé dépendent du caractère. Pour se faire, il suffit au lieu d'additionner une constante d'utiliser une fonction. Par exemple de multiplier par 2, le nombre ASCII associé au caractère. La clé devient alors une fonction: l'exemple f(x)=2*x. 

*Attention*: La fonction doit être invertible sinon il n'est pas possible de décoder le message.   

Créer des programmes qui codent et décodent avec une fonction de votre choix.

In [13]:
def chiffrage_fct(mot):
    mot_chi=""
    mot=mot.upper()
    for i in mot:
        nbr= ord(i)
        if nbr%2==0:
            nbr-=32
        else : 
            nbr+=32 
        mot_chi+=str(chr(nbr))
        print(i, str(chr(nbr)))
    return mot_chi

def dechiffrage_fct(mot_chi):
    mot=""
    for i in mot_chi: 
        nbr = ord(i)
        if nbr>96: 
            nbr-=32
        else:
            nbr+=32
        mot+=str(chr(nbr))
        
    return mot
mot="CHEVAL"
print(" ")      
print(mot)
a=chiffrage_fct(mot)
print(a)
a_dec=dechiffrage_fct(mot)
print(a_dec)


 
CHEVAL
C c
H (
E e
V 6
A a
L ,
c(e6a,
cheval
